# Setup
title:        Kendra Dujmovic
tagline:      A psychology-oriented entrepreneurial marketing professional
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Kendra Dujmovic
  url:        https://kendradujmovic.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown